name: Build and Publish Packages

on:
  push:
    tags: ["*.*.*"]
    branches:
      - main

jobs:
  build:
    permissions: 
      contents: write
      packages: write
      actions: write

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install go
      uses: actions/setup-go@v2
      with:
        go-version: "1.26"
      id: go
    
    - name: Install NPM
      uses: actions/setup-node@v6
      with:
        node-version: "24"
        cache: "npm"
        cache-dependency-path: ui/package-lock.json
      id: node

    - name: Install docker
      uses: docker/setup-buildx-action@v2
    
    - name: Login to GHCR
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        registry: docker.io
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    
    - name: Login to cycr
      uses: docker/login-action@v2
      with:
        registry: cycr.io
        username: ${{ secrets.CYCR_USERNAME }}
        password: ${{ secrets.CYCR_PASSWORD }}
    
    - name: Build NPM
      working-directory: ui
      run: npm ci && npm run build

    - name: Prepare Go build
      run: |
        go mod tidy
        go mod download
        go tool swag init --generalInfo main.go --output docs

    - name: Goreleaser
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
    - name: Goreleaser (on push to main)
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: goreleaser/goreleaser-action@v2
      with:
        args: release --snapshot
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}